karma/additem/views.py
from flask import render_template, Blueprint, url_for, json, session, jsonify, request, redirect
from karma import db
from datetime import datetime
import random,sys
from karma.pages.forms import ProductForm, HotDealsProduct
from karma.pages.picture_handler import add_pic


additem = Blueprint('additem',__name__)


@additem.route('/addproduct', methods=["POST","GET"])
def add():
    if session['login']:
        form = ProductForm()
        if form.validate_on_submit():
            now = datetime.now()
            now = str(now.strftime("%S%M%H%d%m%Y"))
            item = {
                'productcategory' : form.productcategory.data,
                'productname' : form.productname.data,
                'price' : form.price.data,
                'originalprice' : form.originalprice.data,
                'stock' : form.stock.data,
                'type':form.producttype.data,
                'image' : form.image.data,
                'time': now
            }
            if form.image.data:
                pic = add_pic(form.image.data, form.productname.data)
            picture = url_for('static', filename='category/'+pic)
            item['image'] = picture
            id = random.randint(100000, 1000000000)
            if db.child("brands").child(item['brand']).get().val() == None:
                db.child("brands").child(item['brand']).set(item['brand'])

            if db.child("colors").child(item['color']).get().val() == None:
                db.child("colors").child(item['color']).set(item['color'])

            db.child("products").child(id).set(item)
        return render_template('product.html', form=form)
    else:
        return redirect(url_for('blog.index'))

@additem.route('/addHotDealsProduct', methods=["POST","GET"])
def addHotDealsProduct():
    if session['login']:
        form = HotDealsProduct()
        if form.validate_on_submit():
            now = datetime.now()
            now = str(now.strftime("%S%M%H%d%m%Y"))
            item = {
                'productcategory' : "Hot deals",
                'productname' : form.productname.data,
                'price' : form.price.data,
                'originalprice' : form.originalprice.data,
                'stock' : form.stock.data,
                'type':form.producttype.data,
                'image' : form.image.data,
                'time': now,
                "endDate": json.dumps(form.endDate.data)
            }
            if form.image.data:
                pic = add_pic(form.image.data, form.productname.data)
            picture = url_for('static', filename='category/'+pic)
            item['image'] = picture
            id = random.randint(100000, 1000000000)
            # print(json.dumps(form.releaseDate.data), file=sys.stderr)
            # print("inside addhotdealsproduct", file=sys.stderr)
            db.child("hotdealsproduct").child(id).set(item)
        return render_template('hotdealsproduct.html', form=form)
    else:
        return redirect(url_for('blog.index'))


@additem.route('/addtocart', methods=["POST","GET"])
def addtocart():
    if session['login']:
        productid = request.form['productid']
        userid = session['id']
        if request.form['movetocart']:
            db.child("wishList").child(userid).child(productid).remove()
        check = db.child("cart").child(userid).child(productid).get().val()
        # if request.form['hotdealsproduct']:
        #     data = db.child("hotdealsproduct").child(productid).get().val()
        # else:
        #     data = db.child("products").child(productid).get().val()
        productdata = db.child("products").child(productid).get().val()
        totalprice = db.child("cart").child(userid).child("totalprice").get().val()
        if totalprice == None: 
            totalprice = int(0)
        totalprice = int(totalprice)
        if check == None:
            totalprice += int(productdata["price"]) 
        productdata['count'] = 1
        data2 = db.child("cart").child(userid).get().val()
        if data2 is not None:
            data2[productid] = productdata
            data2['totalprice'] = totalprice
            db.child("cart").child(userid).set(data2)
        else:
            mydata = {}
            mydata[productid] = productdata
            mydata['totalprice'] = totalprice
            db.child("cart").child(userid).set(mydata)
        return redirect(url_for('shop.cart'))

    else:
        return redirect(url_for('pages.login'))


# manage count of product in cart
@additem.route('/incdecqty', methods=['POST','GET'])
def incdecqty():
    productid = request.form['productid']
    type = request.form['type']
    userId = session['id']
    cart = db.child('cart').child(userId).get().val()
    if type == "increment":
        cart[productid]['count'] += 1
        if cart[productid]['count'] > cart[productid]['stock']:
            return jsonify({"error":"Product Get Out Of Stock"})
        cart['totalprice'] += int(cart[productid]['price'])
    else:
        cart['totalprice'] -= int(cart[productid]['price'])
        if(cart[productid]['count'] == 1):
            cart.pop(productid)
        else:
            cart[productid]['count'] -= 1
    
    db.child('cart').child(userId).set(cart)
    return redirect(request.referrer)


@additem.route('/deletefromcart', methods=["POST","GET"])
def deletefromcart():
    if session['login']:
        productid = request.form['productid']
        userid = session['id']
        totalprice = db.child("cart").child(userid).child("totalprice").get().val()
        data = db.child("cart").child(userid).get().val()
        db.child("cart").child(userid).child(productid).remove()
        # if totalprice == None: 
        #     totalprice = int(0)
        totalprice = int(totalprice)
        totalprice -= int(data[productid]["price"])*data[productid]["count"]

        db.child("cart").child(userid).child("totalprice").set(totalprice)
        return redirect(url_for('shop.cart'))
    
    else:
        return redirect(url_for('blog.index'))

@additem.route('/addToWishList', methods=['POST','GET'])
def addToWishList():
    if session['login']:
        productId = request.form['productid']
        userId = session['id']
        productData = db.child('products').child(productId).get().val()
        db.child('wishList').child(userId).child(productId).set(productData)
        return redirect(url_for('shop.wishList'))

    else:
        return redirect(url_for('pages.login'))

@additem.route('/deleteFromWishList', methods=['POST','GET'])
def deleteFromWishList():
    if session['login']:
        productid = request.form['productid']
        userid = session['id']
        db.child("wishList").child(userid).child(productid).remove()
        return redirect(url_for('shop.wishList'))

    else:
        return redirect(url_for('blog.index'))


@additem.route('/filter', methods=["POST","GET"])
def filter():
    if session['login']:
        filter = request.form['filter']
        filtervalue = request.form['filtervalue']
        categories = db.child("categories").get().val()
        products = db.child("products").order_by_child(filter).equal_to(filtervalue).get().val()
        msg = "Results for products of "+filter+" "+filtervalue
        return render_template('category.html', products=products, categories = categories, msg = msg)
    else:
        return redirect(url_for('blog.index'))

@additem.route('/filterprice', methods=["POST","GET"])
def filterprice():
    if session['login']:
        startprice = int(request.form['startprice'])
        endprice = int(request.form['endprice'])
        brands = db.child("brands").get().val()
        colors = db.child("colors").get().val()
        categories = db.child("categories").get().val()
        products = db.child("products").order_by_child('price').start_at(startprice).end_at(endprice).get().val()
        msg = "Results for products in range of $"+str(startprice)+"-"+str(endprice)
        return render_template('category.html', products=products, brands = brands, colors = colors, categories = categories, msg=msg) 
    
    else:
        return redirect(url_for('blog.index'))

karma/blog/views.py
import sys

from flask import render_template, Blueprint, session
import json
import os
from karma import app, db


blog = Blueprint('blog', __name__)

@blog.route('/blogs')
def blogs():
    return render_template('blogs.html')

@blog.route('/singleblog')
def singleblog():
    return render_template('singleblog.html')

@blog.route('/') 
def index():
    # commented due to this error was coming because when we just start the project how id key will be come in session as session is empty in starting
    # if session['id'] == None:
    #     session['login'] = False
    filename = os.path.join(app.static_folder, 'json/feature.json') 
    f = open(filename) 
    file = json.load(f) 
    products = db.child("products").get().val()
    hotdealsproductfromDB = db.child('hotdealsproduct').get().val()
    unpackedproduct = {}
    hotdealsid = ""
    hotdealsproducts = {}
    for key,value in hotdealsproductfromDB.items():
        for keyinner, valueinner in value.items():
            hotdealsproducts[keyinner] = valueinner
    #     hotdealsid = key
    # hotdealsproduct = {
    #     'hotdealsimage' : unpackedproduct['image'],
    #     'hotdealsname': unpackedproduct['productname'],
    #     'hotdealsprice': unpackedproduct['price'],
    #     'hotdealsoriginalprice': unpackedproduct['originalprice'],
    #     'hotdealsreleasedate': unpackedproduct['releaseDate']
    # }
    return render_template('index.html', data=file , hotdealsproducts = hotdealsproductfromDB, products=products)

    

karma/pages/views.py
import sys

from flask import render_template, redirect, url_for, session, jsonify, Blueprint
from karma.pages.forms import RegisterForm, LoginForm
from karma import db, auth
import bcrypt


pages = Blueprint('pages', __name__)



# hashing password to store in DB
def create_bcrypt_hash(password):
    password_bytes = password.encode()
    salt = bcrypt.gensalt(14)
    password_hash_bytes = bcrypt.hashpw(password_bytes, salt)
    password_hash_str = password_hash_bytes.decode()

    return password_hash_str


@pages.route('/register', methods=['POST','GET'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # encrypted_password = create_bcrypt_hash(form.password.data)
        user = {
            'username' : form.username.data,
            'email' : form.email.data,
            'password' : form.password.data,
            'confirmpassword' : form.confirmpassword.data,
            'address' : form.address.data,
        }

        users = auth.create_user_with_email_and_password(user['email'], user['password'])
        db.child("users").child(users['localId']).set(user) 
        return redirect(url_for('pages.login'))

    return render_template('register.html', form = form)



@pages.route('/login', methods=['POST','GET'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        try:
            login = auth.sign_in_with_email_and_password(email, password)
            user = db.child("users").child(login['localId']).get().val()
            session['username'] = user['username']
            session['email'] = email
            session['login'] = True
            session['id'] = login['localId']
            if (user['address'] != None):
                # formatting address in session to display it in ordersummary page
                session['address'] = user['address']['name'] + "," + user['address']['address'] + "," + user['address'][
                    'city'] + ',' + user['address']['state'] + "," + str(user['address']['pincode'])
                # session['address'] = user['address']
            return redirect(url_for('blog.index'))
        except:
            return render_template('login.html', form=form, error = "Bad credentials. Please try again")
    return render_template('login.html', form=form, error=None)

@pages.route('/logout')
def logout():
    session.clear()
    session['login'] = False
    return redirect(url_for('blog.index'))

@pages.route('/about')
def about():
    return render_template('about.html')

karma/shop/views.py
from flask import render_template,  Blueprint, session, redirect, url_for
from karma import db
import json
shop = Blueprint('shop', __name__)


@shop.route('/category', methods=["POST","GET"])
def category():
        products = db.child("products").get().val()
        categories = db.child("categories").get().val()
        return render_template('category.html', products=products, categories = categories)


@shop.route('/cart', methods=["POST","GET"])
def cart():
    if session['login']:
        userid = session['id']
        data = db.child("cart").child(session['id']).get().val()
        if data != None:
            totalprice = data['totalprice']
        else:
            totalprice = 0 
        if data:
            data.pop("totalprice")
        session['data'] = data
        session['totalprice'] = totalprice
        return render_template('cart.html', data = data, totalprice=totalprice)
    else:
        return redirect(url_for('pages.login'))


@shop.route('/wishList', methods=["POST","GET"])
def wishList():
    if session['login']:
        wldata = db.child('wishList').child(session['id']).get().val()
        return render_template('wishList.html', data = wldata)
    else:
        return  redirect(url_for('pages.login'))

karma/templates/cart.html
{% extends "base.html" %}

{% block content %}
<!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Shopping Cart</h1>
                    <nav class="d-flex align-items-center">
                        <a href="/">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="{{url_for('shop.cart')}}">Cart</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Cart Area =================-->
    {% if data %}
    <section class="cart_area">
        <div class="container">
            <div class="cart_inner">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Product</th>
                                <th scope="col">Price</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Total</th>
                                <th scope="col">Remove Item</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Row Start -->

                        {% for items in data %}
                            <tr>
                                <td>
                                    <div class="media">
                                        <div class="d-flex">
                                            <img class="cart_image" src="..{{data[items]['image']}}" alt="">
                                        </div>
                                        <div class="media-body">
                                            <p>{{data[items]['productname']}}</p>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <h5>&#8377;{{data[items]['price']}}</h5>
                                </td>
                                <td>
                                    <div class="product_count">
                                        <input type="text" name="qty" maxlength="12" value="{{data[items]['count']}}" title="Quantity:"
                                            class="input-text qty" disabled>
                                            <form action="{{url_for('additem.incdecqty')}}" method="POST">
                                                <input type="hidden" name="productid" value={{items}}>
                                                <input type="hidden" name="type" value="increment">
                                                <button class="increase items-count"><i class="lnr lnr-chevron-up"></i></button>
                                            </form>
                                            <form action="{{url_for('additem.incdecqty')}}" method="POST">
                                                <input type="hidden" name="productid" value={{items}}>
                                                <input type="hidden" name="type" value="decrement">
                                                <button class="reduced items-count"><i class="lnr lnr-chevron-down"></i></button>
                                            </form>
                                    </div>
                                </td>
                                <td>
                                    <h5>&#8377;{{data[items]['count']*data[items]['price']}}</h5>
                                </td>
                                <td>
                                    <form method="POST" action="{{url_for('additem.deletefromcart')}}"> 
                                        <input type="hidden" name="productid" value={{items}}>
                                        <button class="gray_btn">REMOVE</button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                            <!-- End Row -->
                            <tr class="bottom_button">
                                <td>
<!--                                    <a class="gray_btn" href="#">Update Cart</a>-->
                                </td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>
                                    <div class="cupon_text d-flex align-items-center">
                                        <input type="text" placeholder="Coupon Code">
                                        <a class="primary-btn" href="#">Apply</a>
                                        <a class="gray_btn" href="#">Close Coupon</a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>
                                    <h4 style="font-weight: 600;">TOTAL AMOUNT</h4>
                                </td>
                                <td>
                                    <h4 style="font-weight: 600;">&#8377;{{totalprice}}</h4>
                                </td>
                            </tr>
<!--                            <tr class="shipping_area">-->
<!--                                <td></td>-->
<!--                                <td></td>-->
<!--                                <td>-->
<!--                                    <h5>Shipping</h5>-->
<!--                                </td>-->
<!--                                <td></td>-->
<!--                                <td>-->
<!--                                    <div class="shipping_box">-->
<!--                                        <ul class="list">-->
<!--                                            <li><a href="#">Flat Rate: &#8377;5.00</a></li>-->
<!--                                            <li><a href="#">Free Shipping</a></li>-->
<!--                                            <li><a href="#">Flat Rate: &#8377;10.00</a></li>-->
<!--                                            <li class="active"><a href="#">Local Delivery: &#8377;2.00</a></li>-->
<!--                                        </ul>-->
<!--                                        <h6>Calculate Shipping <i class="fa fa-caret-down" aria-hidden="true"></i></h6>-->
<!--                                        <select name='location' class="shipping_select">-->
<!--                                            <option value="1">Bangladesh</option>-->
<!--                                            <option value="2">India</option>-->
<!--                                            <option value="4">Pakistan</option>-->
<!--                                        </select>-->
<!--                                        <select class="shipping_select">-->
<!--                                            <option value="1">Select a State</option>-->
<!--                                            <option value="2">Select a State</option>-->
<!--                                            <option value="4">Select a State</option>-->
<!--                                        </select>-->
<!--                                        <input type="text" placeholder="Postcode/Zipcode">-->
<!--                                        <a class="gray_btn" href="#">Update Details</a>-->
<!--                                    </div>-->
<!--                                </td>-->
<!--                            </tr>-->
                            <tr class="out_button_area">
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>
                                    <div class="checkout_btn_inner d-flex align-items-center">
                                        <a class="gray_btn" href="{{url_for('blog.index')}}">Continue Shopping</a> <hr>
                                        <form action="{{url_for('payment.orderSummary')}}" method="POST" >
                                            <input type="hidden" name="totalprice" value={{totalprice}}>
                                            <input type="hidden" name="payment" value="notpaymentpage">
                                            <button type="submit"  class="primary-btn">Place Order</button>
                                        </form>
                                
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% else %}
        <h1 class="p-3"><center>You Don't Have any Product In Your Cart</center></h1> <br> <br>
        <div class="checkout_btn_inner d-flex justify-content-center">
            <a class="btn btn-dark" href="{{url_for('blog.index')}}">CONTINUE SHOPPING</a>
        </div>
    </section>
    {% endif %}
    <!--================End Cart Area =================-->
    {% endblock %}

karma/templates/category.html
{% extends "base.html" %}

{% block content %}

<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Shop Category page</h1>
					<nav class="d-flex align-items-center">
						<a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="#">Shop<span class="lnr lnr-arrow-right"></span></a>
						<a href="category.html">Fashion Category</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->
	<div class="container section_gap">
		<div class="row">
			<div class="col-xl-3 col-lg-4 col-md-5">
				<div class="sidebar-categories">
					<div class="head">Browse Categories</div>
					<ul class="main-categories p-4">
						<div class="p-1">
						    <a class="btn btn-outline-dark btn-sm" href="{{url_for('shop.category')}}">All</a>
					    </div>
						{% if categories %} 
		    	        {% for category in categories %} 
						<form method="POST" action="{{url_for('additem.filter')}}"> 
							<input type="hidden" name="filter" value="productcategory"> 
							<input type="hidden" name="filtervalue" value={{category}}>

							<div class="p-1">
							    <li class="filter-list"><label for="apple"><button class="btn btn-outline-dark btn-sm">{{category.upper()}}</button></label></li>
							</div>
						</form> 
						{% endfor %} 
					{% endif %} 
					</ul> 
				</div>
				<div class="sidebar-filter mt-50">
					<div class="top-filter-head">Product Filters</div>
					<div class="common-filter">
						<div class="head">Price</div>
						<div class="price-range-area">
							<div id="price-range"></div>
							<div class="value-wrapper d-flex">
								<form method="POST" action="{{url_for('additem.filterprice')}}">
									<div class="input-group">
										<span class="input-group-text">Price : </span>
									    <input name="startprice" class="form-control" type="number" placeholder="Min"> 
									    <input name="endprice" class="form-control" type="number" placeholder="Max">  
								    </div>
									<div class="p-3 d-flex justify-content-center">
									    <button class="btn btn-dark">Submit</button>
								    </div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xl-9 col-lg-8 col-md-7">
				<!-- Start Filter Bar -->
				<div class="filter-bar d-flex flex-wrap align-items-center">
					<!-- <div class="sorting">
						<select>
							<option value="1">Default sorting</option>
							<option value="1">Default sorting</option>
							<option value="1">Default sorting</option>
						</select>
					</div>
					<div class="sorting mr-auto">
						<select>
							<option value="1">Show 12</option>
							<option value="1">Show 12</option>
							<option value="1">Show 12</option>
						</select>
					</div> -->
					<div class="pagination">
						<a href="#" class="prev-arrow"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>
						<a href="#" class="active">1</a>
						<a href="#">2</a>
						<a href="#">3</a>
						<a href="#" class="dot-dot"><i class="fa fa-ellipsis-h" aria-hidden="true"></i></a>
						<a href="#">6</a>
						<a href="#" class="next-arrow"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>
					</div>
				</div>
				<!-- End Filter Bar -->
				<!-- Start Best Seller -->
				{% if msg %}
	                <h1 style="padding-top: 2rem;"><center>{{msg}}</center></h1>
	            {% endif %}
				<section class="lattest-product-area pb-40 category-list">
					<div class="row">
						<!-- single product -->
					{% if products %}
					{% for item in products %}

						<div class="col-lg-4 col-md-6">
							<div class="single-product">
								<img class="img-fluid" src="..{{products[item]["image"]}}" alt="">
								<div class="product-details">
									<h6>{{products[item]["productname"]}}</h6>
									<div class="price">
										<h6>${{products[item]["price"]}}</h6>
										<h6 class="l-through">${{products[item]["originalprice"]}}</h6>
									</div>
									<div class="prd-bottom">

										<a class="social-info">
											<span class="ti-bag"></span>
											<form method="POST" action="{{url_for('additem.addtocart')}}"> 
												<input type="hidden" name="productid" value={{item}}>
												<input type="hidden" name="movetocart" value="">
												<input type="hidden" name="hotdealsproduct" value="">
												<button class="hover-text btn btn-outline-dark btn-sm">add to bag</button>
											</form>
										</a>
										<a class="social-info">
											<span class="lnr lnr-heart"></span>
											<form method="POST" action="{{url_for('additem.addToWishList')}}">
												 <input type="hidden" name="productid" value={{item}}>
												 <p class="hover-text"><button type="submit">add to wishlist</button></p>
											</form>
										</a>

									</div>
								</div>
							</div>
						</div>
                    {% endfor %}
					{% endif %}
					</div>
				</section>
				<!-- End Best Seller -->
				<!-- Start Filter Bar -->
				<div class="filter-bar d-flex flex-wrap align-items-center">
					<div class="sorting mr-auto">
						<select>
							<option value="1">Show 12</option>
							<option value="1">Show 12</option>
							<option value="1">Show 12</option>
						</select>
					</div>
					<div class="pagination">
						<a href="#" class="prev-arrow"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>
						<a href="#" class="active">1</a>
						<a href="#">2</a>
						<a href="#">3</a>
						<a href="#" class="dot-dot"><i class="fa fa-ellipsis-h" aria-hidden="true"></i></a>
						<a href="#">6</a>
						<a href="#" class="next-arrow"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>
					</div>
				</div>
				<!-- End Filter Bar -->
			</div>
		</div>
	</div>

{% endblock %}

karma/templates/login.html
{% extends "base.html" %}

{% block content %}
	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Login</h1>
					<nav class="d-flex align-items-center">
						<a href="/">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="{{url_for('pages.register')}}">Register</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

	<!--================Login Box Area =================-->
	<section class="login_box_area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="login_box_img">
						<img class="img-fluid" src="../static/img/login.jpg" alt="">
						<div class="hover">
							<h4>New to our website?</h4>
							<p>There are advances being made in science and technology everyday, and a good example of this is the</p>
							<a class="primary-btn" href="{{url_for('pages.register')}}">Create an Account</a>
						</div>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="login_form_inner">
						<h3>Log in to enter</h3>
						{% if error %}
						<div class="d-flex justify-content-center">
						<div class="alert alert-danger center" role="alert" style="width:60%">
							{{error}}
						</div>
							</div>
						{% endif %}
						<form class="row login_form" action="{{url_for('pages.login')}}" method="POST" id="contactForm" novalidate="novalidate">
							{{ form.hidden_tag() }}
							<div class="col-md-12 form-group">
								{{ form.email(class="form-control") }}
							</div>
							<div class="col-md-12 form-group">
								{{ form.password(class="form-control") }}	
							</div>
							<!-- <div class="col-md-12 form-group">
								<div class="creat_account">
									<input type="checkbox" id="f-option2" name="selector">
									<label for="f-option2">Keep me logged in</label>
								</div>
							</div> -->
							<div class="col-md-12 form-group">
								{{ form.submit(class="primary-btn") }}
								<a href="#">Forgot Password?</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================End Login Box Area =================-->

{% endblock %}